config/routes.rb
Rails.application.routes.draw do

  resources :assignments
  resources :check_ins
  resources :officers
  resources :agency_contacts
  resources :jobs
  resources :retail_loss_prevention_managers
  resources :store_managers
  resources :locations
  root 'application#hello'

end

app/models/store_manager.rb
class StoreManager < ActiveRecord::Base
  belongs_to :location
end

app/controllers/store_managers_controller.rb
class StoreManagersController < ApplicationController
  before_action :set_store_manager, only: [:show, :edit, :update, :destroy]

  # GET /store_managers
  # GET /store_managers.json
  def index
    @store_managers = StoreManager.all
  end

  # GET /store_managers/1
  # GET /store_managers/1.json
  def show
  end

  # GET /store_managers/new
  def new
    @store_manager = StoreManager.new
  end

  # GET /store_managers/1/edit
  def edit
  end

  # POST /store_managers
  # POST /store_managers.json
  def create
    @store_manager = StoreManager.new(store_manager_params)

    respond_to do |format|
      if @store_manager.save
        format.html { redirect_to @store_manager, notice: 'Store manager was successfully created.' }
        format.json { render :show, status: :created, location: @store_manager }
      else
        format.html { render :new }
        format.json { render json: @store_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_managers/1
  # PATCH/PUT /store_managers/1.json
  def update
    respond_to do |format|
      if @store_manager.update(store_manager_params)
        format.html { redirect_to @store_manager, notice: 'Store manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_manager }
      else
        format.html { render :edit }
        format.json { render json: @store_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_managers/1
  # DELETE /store_managers/1.json
  def destroy
    @store_manager.destroy
    respond_to do |format|
      format.html { redirect_to store_managers_url, notice: 'Store manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_manager
      @store_manager = StoreManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_manager_params
      params.require(:store_manager).permit(:email, :phone, :name, :location_id)
    end
end

app/helpers/store_managers_helper.rb
module StoreManagersHelper
end

app/views/store_managers/_form.html.erb
<%= form_for(@store_manager) do |f| %>
  <% if @store_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store_manager.errors.count, "error") %> prohibited this store_manager from being saved:</h2>

      <ul>
      <% @store_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone;string %><br>
    <%= f.text_field :phone;string %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/store_managers/edit.html.erb
<h1>Editing Store Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @store_manager %> |
<%= link_to 'Back', store_managers_path %>

app/views/store_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Store Managers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Phone;string</th>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @store_managers.each do |store_manager| %>
      <tr>
        <td><%= store_manager.email %></td>
        <td><%= store_manager.phone;string %></td>
        <td><%= store_manager.name %></td>
        <td><%= store_manager.location_id %></td>
        <td><%= link_to 'Show', store_manager %></td>
        <td><%= link_to 'Edit', edit_store_manager_path(store_manager) %></td>
        <td><%= link_to 'Destroy', store_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store manager', new_store_manager_path %>

app/views/store_managers/new.html.erb
<h1>New Store Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', store_managers_path %>

app/views/store_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @store_manager.email %>
</p>

<p>
  <strong>Phone;string:</strong>
  <%= @store_manager.phone;string %>
</p>

<p>
  <strong>Name:</strong>
  <%= @store_manager.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @store_manager.location_id %>
</p>

<%= link_to 'Edit', edit_store_manager_path(@store_manager) %> |
<%= link_to 'Back', store_managers_path %>