config/routes.rb
Rails.application.routes.draw do

  resources :assignments
  resources :check_ins
  resources :officers
  resources :agency_contacts
  resources :jobs
  resources :retail_loss_prevention_managers
  resources :store_managers
  resources :locations
  root 'application#hello'

end

app/models/agency_contact.rb
class AgencyContact < ActiveRecord::Base
  belongs_to :location
  has_many :officers
end

app/controllers/agency_contacts_controller.rb
class AgencyContactsController < ApplicationController
  before_action :set_agency_contact, only: [:show, :edit, :update, :destroy]

  # GET /agency_contacts
  # GET /agency_contacts.json
  def index
    @agency_contacts = AgencyContact.all
  end

  # GET /agency_contacts/1
  # GET /agency_contacts/1.json
  def show
  end

  # GET /agency_contacts/new
  def new
    @agency_contact = AgencyContact.new
  end

  # GET /agency_contacts/1/edit
  def edit
  end

  # POST /agency_contacts
  # POST /agency_contacts.json
  def create
    @agency_contact = AgencyContact.new(agency_contact_params)

    respond_to do |format|
      if @agency_contact.save
        format.html { redirect_to @agency_contact, notice: 'Agency contact was successfully created.' }
        format.json { render :show, status: :created, location: @agency_contact }
      else
        format.html { render :new }
        format.json { render json: @agency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agency_contacts/1
  # PATCH/PUT /agency_contacts/1.json
  def update
    respond_to do |format|
      if @agency_contact.update(agency_contact_params)
        format.html { redirect_to @agency_contact, notice: 'Agency contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency_contact }
      else
        format.html { render :edit }
        format.json { render json: @agency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agency_contacts/1
  # DELETE /agency_contacts/1.json
  def destroy
    @agency_contact.destroy
    respond_to do |format|
      format.html { redirect_to agency_contacts_url, notice: 'Agency contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency_contact
      @agency_contact = AgencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_contact_params
      params.require(:agency_contact).permit(:name, :phone, :email, :location_id)
    end
end

app/helpers/agency_contacts_helper.rb
module AgencyContactsHelper
end

app/views/agency_contacts/_form.html.erb
<%= form_for(@agency_contact) do |f| %>
  <% if @agency_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agency_contact.errors.count, "error") %> prohibited this agency_contact from being saved:</h2>

      <ul>
      <% @agency_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agency_contacts/edit.html.erb
<h1>Editing Agency Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @agency_contact %> |
<%= link_to 'Back', agency_contacts_path %>

app/views/agency_contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agency Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agency_contacts.each do |agency_contact| %>
      <tr>
        <td><%= agency_contact.name %></td>
        <td><%= agency_contact.phone %></td>
        <td><%= agency_contact.email %></td>
        <td><%= agency_contact.location_id %></td>
        <td><%= link_to 'Show', agency_contact %></td>
        <td><%= link_to 'Edit', edit_agency_contact_path(agency_contact) %></td>
        <td><%= link_to 'Destroy', agency_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency contact', new_agency_contact_path %>

app/views/agency_contacts/new.html.erb
<h1>New Agency Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', agency_contacts_path %>

app/views/agency_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agency_contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agency_contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @agency_contact.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @agency_contact.location_id %>
</p>

<%= link_to 'Edit', edit_agency_contact_path(@agency_contact) %> |
<%= link_to 'Back', agency_contacts_path %>