config/routes.rb
Rails.application.routes.draw do

  resources :assignments
  resources :check_ins
  resources :officers
  resources :agency_contacts
  resources :jobs
  resources :retail_loss_prevention_managers
  resources :store_managers
  resources :locations
  root 'application#hello'

end

app/models/retail_loss_prevention_manager.rb
class RetailLossPreventionManager < ActiveRecord::Base
  belongs_to :location
end

app/controllers/retail_loss_prevention_managers_controller.rb
class RetailLossPreventionManagersController < ApplicationController
  before_action :set_retail_loss_prevention_manager, only: [:show, :edit, :update, :destroy]

  # GET /retail_loss_prevention_managers
  # GET /retail_loss_prevention_managers.json
  def index
    @retail_loss_prevention_managers = RetailLossPreventionManager.all
  end

  # GET /retail_loss_prevention_managers/1
  # GET /retail_loss_prevention_managers/1.json
  def show
  end

  # GET /retail_loss_prevention_managers/new
  def new
    @retail_loss_prevention_manager = RetailLossPreventionManager.new
  end

  # GET /retail_loss_prevention_managers/1/edit
  def edit
  end

  # POST /retail_loss_prevention_managers
  # POST /retail_loss_prevention_managers.json
  def create
    @retail_loss_prevention_manager = RetailLossPreventionManager.new(retail_loss_prevention_manager_params)

    respond_to do |format|
      if @retail_loss_prevention_manager.save
        format.html { redirect_to @retail_loss_prevention_manager, notice: 'Retail loss prevention manager was successfully created.' }
        format.json { render :show, status: :created, location: @retail_loss_prevention_manager }
      else
        format.html { render :new }
        format.json { render json: @retail_loss_prevention_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /retail_loss_prevention_managers/1
  # PATCH/PUT /retail_loss_prevention_managers/1.json
  def update
    respond_to do |format|
      if @retail_loss_prevention_manager.update(retail_loss_prevention_manager_params)
        format.html { redirect_to @retail_loss_prevention_manager, notice: 'Retail loss prevention manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @retail_loss_prevention_manager }
      else
        format.html { render :edit }
        format.json { render json: @retail_loss_prevention_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /retail_loss_prevention_managers/1
  # DELETE /retail_loss_prevention_managers/1.json
  def destroy
    @retail_loss_prevention_manager.destroy
    respond_to do |format|
      format.html { redirect_to retail_loss_prevention_managers_url, notice: 'Retail loss prevention manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retail_loss_prevention_manager
      @retail_loss_prevention_manager = RetailLossPreventionManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retail_loss_prevention_manager_params
      params.require(:retail_loss_prevention_manager).permit(:phone, :email, :location_id)
    end
end

app/helpers/retail_loss_prevention_managers_helper.rb
module RetailLossPreventionManagersHelper
end

app/views/retail_loss_prevention_managers/_form.html.erb
<%= form_for(@retail_loss_prevention_manager) do |f| %>
  <% if @retail_loss_prevention_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retail_loss_prevention_manager.errors.count, "error") %> prohibited this retail_loss_prevention_manager from being saved:</h2>

      <ul>
      <% @retail_loss_prevention_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/retail_loss_prevention_managers/edit.html.erb
<h1>Editing Retail Loss Prevention Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @retail_loss_prevention_manager %> |
<%= link_to 'Back', retail_loss_prevention_managers_path %>

app/views/retail_loss_prevention_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Retail Loss Prevention Managers</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Email</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @retail_loss_prevention_managers.each do |retail_loss_prevention_manager| %>
      <tr>
        <td><%= retail_loss_prevention_manager.phone %></td>
        <td><%= retail_loss_prevention_manager.email %></td>
        <td><%= retail_loss_prevention_manager.location_id %></td>
        <td><%= link_to 'Show', retail_loss_prevention_manager %></td>
        <td><%= link_to 'Edit', edit_retail_loss_prevention_manager_path(retail_loss_prevention_manager) %></td>
        <td><%= link_to 'Destroy', retail_loss_prevention_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Retail loss prevention manager', new_retail_loss_prevention_manager_path %>

app/views/retail_loss_prevention_managers/new.html.erb
<h1>New Retail Loss Prevention Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', retail_loss_prevention_managers_path %>

app/views/retail_loss_prevention_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @retail_loss_prevention_manager.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @retail_loss_prevention_manager.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @retail_loss_prevention_manager.location_id %>
</p>

<%= link_to 'Edit', edit_retail_loss_prevention_manager_path(@retail_loss_prevention_manager) %> |
<%= link_to 'Back', retail_loss_prevention_managers_path %>